"""make_demographics_nullable

Revision ID: 1ee7ae8b471d
Revises: 732e7807896d
Create Date: 2026-04-30 16:59:23.212521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ee7ae8b471d'
down_revision: Union[str, Sequence[str], None] = '732e7807896d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'fecha_nacimiento',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text("'2000-01-01'::date"))
    op.alter_column('usuarios', 'sexo',
               existing_type=postgresql.ENUM('masculino', 'femenino', 'no_binario', 'prefiero_no_decir', name='sexo_enum'),
               nullable=True,
               existing_server_default=sa.text("'prefiero_no_decir'::sexo_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'sexo',
               existing_type=postgresql.ENUM('masculino', 'femenino', 'no_binario', 'prefiero_no_decir', name='sexo_enum'),
               nullable=False,
               existing_server_default=sa.text("'prefiero_no_decir'::sexo_enum"))
    op.alter_column('usuarios', 'fecha_nacimiento',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text("'2000-01-01'::date"))
    # ### end Alembic commands ###
