"""add_ipc_cache_table

Revision ID: 4ea4f7e4ec0f
Revises: 75381af94d37
Create Date: 2026-06-05 19:00:16.605780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea4f7e4ec0f'
down_revision: Union[str, Sequence[str], None] = '75381af94d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipc_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('valor_mensual', sa.Float(), nullable=False),
    sa.Column('fecha_dato', sa.String(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fuente', sa.String(), nullable=False),
    sa.Column('es_estimado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipc_cache')
    # ### end Alembic commands ###
