"""add_notification_system_complete

Revision ID: 5e22b239aa5e
Revises: 329646d68fe9
Create Date: 2026-06-08 22:43:59.224379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e22b239aa5e'
down_revision: Union[str, Sequence[str], None] = '329646d68fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the new enum types first
    tipo_enum = postgresql.ENUM('CAMBIO_CONTRASENA', 'NUEVO_DISPOSITIVO', 'CAMBIO_EMAIL', 'INTENTOS_LOGIN_FALLIDOS', 'WHATSAPP_NUEVO_VINCULADO', 'CUOTA_VENCE', 'PRESUPUESTO_AGOTADO', 'SALDO_CERO', 'SUSCRIPCION_HOY', 'PRESUPUESTO_LIMITE', 'SUSCRIPCION_PROXIMA', 'RESUMEN_SEMANAL', 'META_ALCANZADA', 'GASTO_INUSUAL', 'INACTIVIDAD', name='tipo_notificacion_sa_enum')
    tipo_enum.create(op.get_bind(), checkfirst=True)
    nivel_enum = postgresql.ENUM('CRITICA', 'FINANCIERA_IMPORTANTE', 'FINANCIERA_INFORMATIVA', 'SOFT', name='nivel_notificacion_sa_enum')
    nivel_enum.create(op.get_bind(), checkfirst=True)

    op.drop_table('ipc_cache')
    op.add_column('configuracion_notificaciones', sa.Column('suscripcion_hoy_web', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('configuracion_notificaciones', sa.Column('suscripcion_hoy_whatsapp', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index('ix_config_notif_whatsapp_hora', 'configuracion_notificaciones', ['whatsapp_hora_envio'], unique=False)
    op.drop_column('configuracion_notificaciones', 'saldo_cero_activo')
    op.drop_index(op.f('ix_cuotas_grupo_vencimiento'), table_name='cuotas', postgresql_where='(pagada = false)')
    op.drop_index(op.f('ix_grupos_cuotas_tarjeta_usuario'), table_name='grupos_cuotas')
    op.drop_index(op.f('ix_historial_suscripcion_id_fecha'), table_name='historial_suscripciones')
    op.alter_column('notificaciones', 'tipo',
               existing_type=postgresql.ENUM('CAMBIO_CONTRASENA', 'NUEVO_DISPOSITIVO', 'CAMBIO_EMAIL', 'INTENTOS_LOGIN_FALLIDOS', 'WHATSAPP_NUEVO_VINCULADO', 'CUOTA_VENCE', 'PRESUPUESTO_AGOTADO', 'SALDO_CERO', 'SUSCRIPCION_HOY', 'PRESUPUESTO_LIMITE', 'SUSCRIPCION_PROXIMA', 'RESUMEN_SEMANAL', 'META_ALCANZADA', 'GASTO_INUSUAL', 'INACTIVIDAD', name='tipo_notificacion_enum'),
               type_=sa.Enum('CAMBIO_CONTRASENA', 'NUEVO_DISPOSITIVO', 'CAMBIO_EMAIL', 'INTENTOS_LOGIN_FALLIDOS', 'WHATSAPP_NUEVO_VINCULADO', 'CUOTA_VENCE', 'PRESUPUESTO_AGOTADO', 'SALDO_CERO', 'SUSCRIPCION_HOY', 'PRESUPUESTO_LIMITE', 'SUSCRIPCION_PROXIMA', 'RESUMEN_SEMANAL', 'META_ALCANZADA', 'GASTO_INUSUAL', 'INACTIVIDAD', name='tipo_notificacion_sa_enum'),
               existing_nullable=False,
               postgresql_using="tipo::text::tipo_notificacion_sa_enum")
    op.alter_column('notificaciones', 'nivel',
               existing_type=postgresql.ENUM('CRITICA', 'FINANCIERA_IMPORTANTE', 'FINANCIERA_INFORMATIVA', 'SOFT', name='nivel_notificacion_enum'),
               type_=sa.Enum('CRITICA', 'FINANCIERA_IMPORTANTE', 'FINANCIERA_INFORMATIVA', 'SOFT', name='nivel_notificacion_sa_enum'),
               existing_nullable=False,
               postgresql_using="nivel::text::nivel_notificacion_sa_enum")
    op.alter_column('notificaciones', 'grupo_agrupacion',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('notificaciones', 'deep_link',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.create_index('ix_notificaciones_usuario_activas', 'notificaciones', ['usuario_id', 'leida', 'archivada'], unique=False)
    op.create_index('ix_notificaciones_usuario_grupo', 'notificaciones', ['usuario_id', 'grupo_agrupacion'], unique=False)
    op.create_index('ix_notificaciones_usuario_no_leidas', 'notificaciones', ['usuario_id', 'leida', 'archivada', 'silenciada_hasta'], unique=False)
    op.create_index('ix_notificaciones_whatsapp_pendientes', 'notificaciones', ['usuario_id', 'canal_whatsapp', 'enviada_whatsapp'], unique=False)
    op.drop_column('notificaciones', 'fecha_creacion')
    op.drop_column('notificaciones', 'modulo_ref')
    op.drop_column('notificaciones', 'titulo')
    op.drop_index(op.f('ix_transacciones_recurrente_fecha'), table_name='transacciones', postgresql_where='(recurrente_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transacciones_recurrente_fecha'), 'transacciones', ['recurrente_id', 'fecha'], unique=False, postgresql_where='(recurrente_id IS NOT NULL)')
    op.add_column('notificaciones', sa.Column('titulo', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('notificaciones', sa.Column('modulo_ref', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('notificaciones', sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index('ix_notificaciones_whatsapp_pendientes', table_name='notificaciones')
    op.drop_index('ix_notificaciones_usuario_no_leidas', table_name='notificaciones')
    op.drop_index('ix_notificaciones_usuario_grupo', table_name='notificaciones')
    op.drop_index('ix_notificaciones_usuario_activas', table_name='notificaciones')
    op.alter_column('notificaciones', 'deep_link',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('notificaciones', 'grupo_agrupacion',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('notificaciones', 'nivel',
               existing_type=sa.Enum('CRITICA', 'FINANCIERA_IMPORTANTE', 'FINANCIERA_INFORMATIVA', 'SOFT', name='nivel_notificacion_sa_enum'),
               type_=postgresql.ENUM('CRITICA', 'FINANCIERA_IMPORTANTE', 'FINANCIERA_INFORMATIVA', 'SOFT', name='nivel_notificacion_enum'),
               existing_nullable=False)
    op.alter_column('notificaciones', 'tipo',
               existing_type=sa.Enum('CAMBIO_CONTRASENA', 'NUEVO_DISPOSITIVO', 'CAMBIO_EMAIL', 'INTENTOS_LOGIN_FALLIDOS', 'WHATSAPP_NUEVO_VINCULADO', 'CUOTA_VENCE', 'PRESUPUESTO_AGOTADO', 'SALDO_CERO', 'SUSCRIPCION_HOY', 'PRESUPUESTO_LIMITE', 'SUSCRIPCION_PROXIMA', 'RESUMEN_SEMANAL', 'META_ALCANZADA', 'GASTO_INUSUAL', 'INACTIVIDAD', name='tipo_notificacion_sa_enum'),
               type_=postgresql.ENUM('CAMBIO_CONTRASENA', 'NUEVO_DISPOSITIVO', 'CAMBIO_EMAIL', 'INTENTOS_LOGIN_FALLIDOS', 'WHATSAPP_NUEVO_VINCULADO', 'CUOTA_VENCE', 'PRESUPUESTO_AGOTADO', 'SALDO_CERO', 'SUSCRIPCION_HOY', 'PRESUPUESTO_LIMITE', 'SUSCRIPCION_PROXIMA', 'RESUMEN_SEMANAL', 'META_ALCANZADA', 'GASTO_INUSUAL', 'INACTIVIDAD', name='tipo_notificacion_enum'),
               existing_nullable=False)
    op.create_index(op.f('ix_historial_suscripcion_id_fecha'), 'historial_suscripciones', ['suscripcion_id', sa.literal_column('vigente_desde DESC')], unique=False)
    op.create_index(op.f('ix_grupos_cuotas_tarjeta_usuario'), 'grupos_cuotas', ['tarjeta_id', 'usuario_id'], unique=False)
    op.create_index(op.f('ix_cuotas_grupo_vencimiento'), 'cuotas', ['grupo_id', 'fecha_vencimiento'], unique=False, postgresql_where='(pagada = false)')
    op.add_column('configuracion_notificaciones', sa.Column('saldo_cero_activo', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index('ix_config_notif_whatsapp_hora', table_name='configuracion_notificaciones')
    op.drop_column('configuracion_notificaciones', 'suscripcion_hoy_whatsapp')
    op.drop_column('configuracion_notificaciones', 'suscripcion_hoy_web')
    op.create_table('ipc_cache',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('valor_mensual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha_dato', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('fuente', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('es_estimado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ipc_cache_pkey'))
    )
    # ### end Alembic commands ###
