"""reset_refresh_tokens

Revision ID: 6febb95b85d5
Revises: cafcf4463cd1
Create Date: 2026-05-04 14:57:27.374391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6febb95b85d5'
down_revision: Union[str, Sequence[str], None] = 'cafcf4463cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.execute("DROP TABLE IF EXISTS refresh_tokens CASCADE")

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("token_id", sa.String(length=64), nullable=False, unique=True),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("fecha_expiracion", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fecha_creacion", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revocado", sa.Boolean(), nullable=False, default=False),
        sa.Column("device_info", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"], ondelete="CASCADE"),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
