"""add_fecha_nacimiento_sexo_usuario

Revision ID: 732e7807896d
Revises: bb7cacf8ca87
Create Date: 2026-04-30 16:35:38.160954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732e7807896d'
down_revision: Union[str, Sequence[str], None] = 'bb7cacf8ca87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear el enum manualmente ya que autogenerate a veces falla con enums en Postgres
    sa.Enum('masculino', 'femenino', 'no_binario', 'prefiero_no_decir', name='sexo_enum').create(op.get_bind())
    
    op.add_column('usuarios', sa.Column('fecha_nacimiento', sa.Date(), server_default='2000-01-01', nullable=False))
    op.add_column('usuarios', sa.Column('sexo', sa.Enum('masculino', 'femenino', 'no_binario', 'prefiero_no_decir', name='sexo_enum'), server_default='prefiero_no_decir', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'sexo')
    op.drop_column('usuarios', 'fecha_nacimiento')
    
    # Eliminar el enum
    sa.Enum(name='sexo_enum').drop(op.get_bind())
    # ### end Alembic commands ###
