"""fundacion_tarjetas

Revision ID: a40d550dae2e
Revises: 7abc12345def
Create Date: 2026-05-05 23:29:32.225477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a40d550dae2e'
down_revision: Union[str, Sequence[str], None] = '7abc12345def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear el tipo enum manualmente
    op.execute("CREATE TYPE moneda_tarjeta_enum AS ENUM ('ARS', 'USD')")
    
    op.alter_column('tarjetas_credito', 'moneda',
               existing_type=postgresql.ENUM('ARS', 'USD', name='moneda_enum'),
               type_=sa.Enum('ARS', 'USD', name='moneda_tarjeta_enum'),
               postgresql_using="moneda::text::moneda_tarjeta_enum",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tarjetas_credito', 'moneda',
               existing_type=sa.Enum('ARS', 'USD', name='moneda_tarjeta_enum'),
               type_=postgresql.ENUM('ARS', 'USD', name='moneda_enum'),
               existing_nullable=False)
    
    # Eliminar el tipo enum manualmente
    op.execute("DROP TYPE moneda_tarjeta_enum")
    # ### end Alembic commands ###
