"""add_password_configurada

Revision ID: bb7cacf8ca87
Revises: 
Create Date: 2026-04-30 16:19:30.430649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_password_configurada

Revision ID: bb7cacf8ca87
Revises: 
Create Date: 2026-04-30 16:19:30.430649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7cacf8ca87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password_configurada', sa.Boolean(), nullable=True))
    op.execute("UPDATE usuarios SET password_configurada = (password_hash IS NOT NULL)")
    op.alter_column('usuarios', 'password_configurada', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'password_configurada')
    # ### end Alembic commands ###
